removed sudo from scripts and modified files to handle tpd.ko, /etc/profile, /etc/modules accordingly, COMMENTED OUT ALL commands in tibbo-oobe.postrm

diff --git a/tibbo-oobe.postrm b/tibbo-oobe.postrm
--- a/tibbo-oobe.postrm
+++ b/tibbo-oobe.postrm
@@ -1,56 +1,60 @@
-#!/bin/sh
-#postrm script for tibbo-oobe
+#!/bin/bash
+# postrm script for tibbo-oobe
 #
-#see: dh_installdeb(1)
+# see: dh_installdeb(1)
+
+#Set source directory
+MODULES_FILENAME="modules"
+PROFILE_FILENAME="profile"
+
+ETC_DIR=/etc
+
+MODULES_FPATH="${ETC_DIR}/${MODULES_FILENAME}"
+PROFILES_FPATH="${ETC_DIR}/${PROFILE_FILENAME}"
 
 set -e
 
-#Define sed commands in an array
-sed_commands=(
-    '/^export LD_LIBRARY_PATH=:\/usr\/lib\/arm-linux-gnueabihf\//d'
-    '/^export PYTHONPATH=:\/usr\/lib\/python3\/ntios\//d'
-    '/^export PL_IO_NUM_9=8/d'
-    '/^export PL_IO_NUM_8=9/d'
-    '/^export PL_IO_NUM_0=10/d'
-    '/^export PL_IO_NUM_16=11/d'
-    '/^export PL_IO_NUM_32=12/d'
-    '/^export PL_IO_NUM_33=13/d'
-    '/^export PL_IO_NUM_4=14/d'
-    '/^export PL_IO_NUM_20=15/d'
-    '/^export PL_IO_NUM_11=16/d'
-    '/^export PL_IO_NUM_10=17/d'
-    '/^export PL_IO_NUM_1=18/d'
-    '/^export PL_IO_NUM_17=19/d'
-    '/^export PL_IO_NUM_34=20/d'
-    '/^export PL_IO_NUM_35=21/d'
-    '/^export PL_IO_NUM_5=22/d'
-    '/^export PL_IO_NUM_21=23/d'
-    '/^export PL_IO_NUM_13=24/d'
-    '/^export PL_IO_NUM_12=25/d'
-    '/^export PL_IO_NUM_2=26/d'
-    '/^export PL_IO_NUM_18=27/d'
-    '/^export PL_IO_NUM_36=28/d'
-    '/^export PL_IO_NUM_37=29/d'
-    '/^export PL_IO_NUM_6=30/d'
-    '/^export PL_IO_NUM_22=31/d'
-    '/^export PL_IO_NUM_15=32/d'
-    '/^export PL_IO_NUM_14=33/d'
-    '/^export PL_IO_NUM_3=34/d'
-    '/^export PL_IO_NUM_19=35/d'
-    '/^export PL_IO_NUM_38=36/d'
-    '/^export PL_IO_NUM_39=37/d'
-    '/^export PL_IO_NUM_7=38/d'
-    '/^export PL_IO_NUM_23=39/d'
-)
 
-#Perform sed commands on /etc/profile
-for cmd in "${sed_commands[@]}"; do
-    sed -i "$cmd" /etc/profile
-done
+# sed -i '/^export LD_LIBRARY_PATH=\$LD_LIBRARY_PATH:\/usr\/lib\/arm-linux-gnueabihf\//d' ${PROFILES_FPATH}
+# sed -i '/^export PYTHONPATH=\$PYTHONPATH:\/usr\/lib\/python3\/ntios\//d' ${PROFILES_FPATH}
+# sed -i '/^export PL_IO_NUM_9=8/d' ${PROFILES_FPATH}
+# sed -i '/^export PL_IO_NUM_8=9/d' ${PROFILES_FPATH}
+# sed -i '/^export PL_IO_NUM_0=10/d' ${PROFILES_FPATH}
+# sed -i '/^export PL_IO_NUM_16=11/d' ${PROFILES_FPATH}
+# sed -i '/^export PL_IO_NUM_32=12/d' ${PROFILES_FPATH}
+# sed -i '/^export PL_IO_NUM_33=13/d' ${PROFILES_FPATH}
+# sed -i '/^export PL_IO_NUM_4=14/d' ${PROFILES_FPATH}
+# sed -i '/^export PL_IO_NUM_20=15/d' ${PROFILES_FPATH}
+# sed -i '/^export PL_IO_NUM_11=16/d' ${PROFILES_FPATH}
+# sed -i '/^export PL_IO_NUM_10=17/d' ${PROFILES_FPATH}
+# sed -i '/^export PL_IO_NUM_1=18/d' ${PROFILES_FPATH}
+# sed -i '/^export PL_IO_NUM_17=19/d' ${PROFILES_FPATH}
+# sed -i '/^export PL_IO_NUM_34=20/d' ${PROFILES_FPATH}
+# sed -i '/^export PL_IO_NUM_35=21/d' ${PROFILES_FPATH}
+# sed -i '/^export PL_IO_NUM_5=22/d' ${PROFILES_FPATH}
+# sed -i '/^export PL_IO_NUM_21=23/d' ${PROFILES_FPATH}
+# sed -i '/^export PL_IO_NUM_13=24/d' ${PROFILES_FPATH}
+# sed -i '/^export PL_IO_NUM_12=25/d' ${PROFILES_FPATH}
+# sed -i '/^export PL_IO_NUM_2=26/d' ${PROFILES_FPATH}
+# sed -i '/^export PL_IO_NUM_18=27/d' ${PROFILES_FPATH}
+# sed -i '/^export PL_IO_NUM_36=28/d' ${PROFILES_FPATH}
+# sed -i '/^export PL_IO_NUM_37=29/d' ${PROFILES_FPATH}
+# sed -i '/^export PL_IO_NUM_6=30/d' ${PROFILES_FPATH}
+# sed -i '/^export PL_IO_NUM_22=31/d' ${PROFILES_FPATH}
+# sed -i '/^export PL_IO_NUM_15=32/d' ${PROFILES_FPATH}
+# sed -i '/^export PL_IO_NUM_14=33/d' ${PROFILES_FPATH}
+# sed -i '/^export PL_IO_NUM_3=34/d' ${PROFILES_FPATH}
+# sed -i '/^export PL_IO_NUM_19=35/d' ${PROFILES_FPATH}
+# sed -i '/^export PL_IO_NUM_38=36/d' ${PROFILES_FPATH}
+# sed -i '/^export PL_IO_NUM_39=37/d' ${PROFILES_FPATH}
+# sed -i '/^export PL_IO_NUM_7=38/d' ${PROFILES_FPATH}
+# sed -i '/^export PL_IO_NUM_23=39/d' ${PROFILES_FPATH}
+# sed -i '/^export PL_IO_NUM_NULL=65/d' ${PROFILES_FPATH}
 
 
+# sed -i '/^tpd/d' ${MODULES_FPATH}
 
-#summary of how this script can be called:
+# summary of how this script can be called:
 #        * <postrm> `remove'
 #        * <postrm> `purge'
 #        * <old-postrm> `upgrade' <new-version>
@@ -60,21 +64,22 @@ done
 #        * <new-postrm> `abort-upgrade' <old-version>
 #        * <disappearer's-postrm> `disappear' <overwriter>
 #          <overwriter-version>
-#for details, see https://www.debian.org/doc/debian-policy/ or
-#the debian-policy package
+# for details, see https://www.debian.org/doc/debian-policy/ or
+# the debian-policy package
 
-case "$1" in
-    purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
-    ;;
 
-    *)
-        echo "postrm called with unknown argument \`$1'" >&2
-        exit 1
-    ;;
-esac
+# case "$1" in
+#     purge|remove|upgrade|failed-upgrade|abort-install|abort-upgrade|disappear)
+#     ;;
 
-#dh_installdeb will replace this with shell code automatically
-#generated by other debhelper scripts.
+#     *)
+#         echo "postrm called with unknown argument \'$1'" >&2
+#         exit 1
+#     ;;
+# esac
+
+# dh_installdeb will replace this with shell code automatically
+# generated by other debhelper scripts.
 
 #DEBHELPER#
 
